# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crowdshot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for crowdshot
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  target 'crowdshotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
